SUBDIRS = test0 test1 test2 test3 test4 test5 test6 iftest fortest

clean:
	rm -rf *~
	make -C test0 clean
	make -C test1 clean
	make -C test2 clean
	make -C test3 clean
	make -C test4 clean
	make -C test5 clean
	make -C test6 clean
	make -C iftest clean
	make -C fortest clean
